#pragma checksum "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0ADD1F3E60CA65F4303DE9C0264868030B706917"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class LoginPage : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
    
    #line default
    #line hidden
    
    
    #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    protected global::System.Web.UI.WebControls.TextBox loginUsername;
    
    #line default
    #line hidden
    
    
    #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
    
    #line default
    #line hidden
    
    
    #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    protected global::System.Web.UI.WebControls.TextBox loginPassword;
    
    #line default
    #line hidden
    
    
    #line 31 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
    
    #line default
    #line hidden
    
    
    #line 37 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    protected global::System.Web.UI.WebControls.Button Button_login;
    
    #line default
    #line hidden
    
    
    #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    protected global::System.Web.UI.WebControls.HyperLink Registraion;
    
    #line default
    #line hidden
    
    
    #line 48 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    protected global::System.Web.UI.WebControls.CheckBox set_cokie;
    
    #line default
    #line hidden
    
    
    #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 334 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 341 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 347 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 346 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 335 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 340 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class loginpage_aspx : global::LoginPage, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.loginpage_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public loginpage_aspx() {
            string[] dependencies;
            
            #line 912304 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/LoginPage.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.loginpage_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/LoginPage.aspx";
                dependencies[1] = "~/LoginPage.aspx.cs";
                global::ASP.loginpage_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.loginpage_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        98,
                        68,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=15.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.loginpage_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.loginpage_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Login Page");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        211,
                        10,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 7 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        204,
                        25,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 9 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 9 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 9 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("media", "screen");
            
            #line default
            #line hidden
            
            #line 9 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.Href = "css/Login.css";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        340,
                        76,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <style type=\"text/css\">\r\n        .login_registration {\r\n            width: " +
                    "175px;\r\n        }\r\n    </style>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        416,
                        114,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControlHead1() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            this.Head1 = @__ctrl;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ID = "Head1";
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl2;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        166,
                        371,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        537,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        <div class=\"login-box\">\r\n            <img src=\"image/user.png\" class=\"u" +
                    "ser\">\r\n            <h1>Login Here</h1>\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        583,
                        133,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n            <p>User Name</p>\r\n\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        743,
                        48,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlloginUsername() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.loginUsername = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ID = "loginUsername";
            
            #line default
            #line hidden
            
            #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "input_name_password");
            
            #line default
            #line hidden
            
            #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter Username");
            
            #line default
            #line hidden
            
            #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(180D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.TextChanged += new System.EventHandler(this.loginUsername_TextChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        791,
                        174,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        965,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ID = "RequiredFieldValidator1";
            
            #line default
            #line hidden
            
            #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ControlToValidate = "loginUsername";
            
            #line default
            #line hidden
            
            #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ErrorMessage = "Please Enter User Name";
            
            #line default
            #line hidden
            
            #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(204, 0, 0)));
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        979,
                        193,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1172,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <p>Password</p>\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1208,
                        43,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlloginPassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.loginPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ID = "loginPassword";
            
            #line default
            #line hidden
            
            #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "input_name_password");
            
            #line default
            #line hidden
            
            #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter Password");
            
            #line default
            #line hidden
            
            #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            
            #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.TextChanged += new System.EventHandler(this.TextBox2_TextChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1251,
                        175,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <br />\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1426,
                        34,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator2() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 31 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 31 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ID = "RequiredFieldValidator2";
            
            #line default
            #line hidden
            
            #line 31 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ControlToValidate = "loginPassword";
            
            #line default
            #line hidden
            
            #line 31 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ErrorMessage = "Please Enter correct password";
            
            #line default
            #line hidden
            
            #line 31 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(204, 0, 0)));
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1460,
                        200,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1660,
                        16,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n            <br />\r\n\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1691,
                        38,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlButton_login() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 37 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.Button_login = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 37 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ID = "Button_login";
            
            #line default
            #line hidden
            
            #line 37 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "login_registration");
            
            #line default
            #line hidden
            
            #line 37 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.Text = "Login";
            
            #line default
            #line hidden
            
            #line 37 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.Click += new System.EventHandler(this.Button_login_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1729,
                        116,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n            <br />\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1845,
                        36,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <div class=\"login_registration\">\r\n                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2022,
                        64,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Registration");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2277,
                        12,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControlRegistraion() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            this.Registraion = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ID = "Registraion";
            
            #line default
            #line hidden
            
            #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.NavigateUrl = "~/Registration.aspx";
            
            #line default
            #line hidden
            
            #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.Font.Size = global::System.Web.UI.WebControls.FontUnit.Medium;
            
            #line default
            #line hidden
            
            #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.EnableTheming = true;
            
            #line default
            #line hidden
            
            #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.Font.Names = new string[] {
                    "Adobe Myungjo Std M"};
            
            #line default
            #line hidden
            
            #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(255, 51, 0)));
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl1 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 42 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2086,
                        219,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control19() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n            </div>\r\n\r\n            <br />\r\n            <div>\r\n                " +
                    "");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2305,
                        81,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlset_cokie() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 48 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.set_cokie = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 48 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ID = "set_cokie";
            
            #line default
            #line hidden
            
            #line 48 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.Text = "Remember me";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2386,
                        78,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            </div>\r\n            <br />\r\n            <a href=\"#\">Forget Password" +
                    "</a>\r\n\r\n\r\n        </div>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2464,
                        111,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl1 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl2;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl2 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl3 = this.@__BuildControlloginUsername();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl4;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl4 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl5;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl5 = this.@__BuildControlRequiredFieldValidator1();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl6;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl6 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl7 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl8 = this.@__BuildControlloginPassword();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl9 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl10;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl10 = this.@__BuildControlRequiredFieldValidator2();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl11 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl12;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl12 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl13;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl13 = this.@__BuildControlButton_login();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl14;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl14 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl15 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl16;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl16 = this.@__BuildControlRegistraion();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl17 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl18;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl18 = this.@__BuildControlset_cokie();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl19;
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl19 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 17 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        551,
                        2031,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control21() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2582,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(loginpage_aspx @__ctrl) {
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl2 = this.@__BuildControlHead1();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl3 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl4 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__ctrl5 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\LoginPage.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.loginpage_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1196610039;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
