#pragma checksum "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "086888A539178D71E98A00FB0698DA145E6DE310"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Menager : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 19 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
    protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceRegistration;
    
    #line default
    #line hidden
    
    
    #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
    protected global::System.Web.UI.WebControls.GridView GridView1;
    
    #line default
    #line hidden
    
    
    #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 334 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 341 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 19 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 347 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 19 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 346 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 335 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 19 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 19 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 340 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 19 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class menager_aspx : global::Menager, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.menager_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public menager_aspx() {
            string[] dependencies;
            
            #line 912304 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Menager.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.menager_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Menager.aspx";
                dependencies[1] = "~/Menager.aspx.cs";
                global::ASP.menager_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.menager_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        94,
                        68,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=15.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.menager_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.menager_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        189,
                        15,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <style type=\"text/css\">\r\n        #form1 {\r\n            height: 746px;\r\n    " +
                    "        width: 1371px;\r\n        }\r\n    </style>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        204,
                        130,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl2;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        162,
                        179,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<body style=\"height: 362px; width: 810px\">\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        341,
                        50,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <div>\r\n    \r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        423,
                        19,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.SqlDataSource @__BuildControlSqlDataSourceRegistration() {
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl;
            
            #line 19 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.SqlDataSource();
            
            #line default
            #line hidden
            this.SqlDataSourceRegistration = @__ctrl;
            
            #line 19 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.ID = "SqlDataSourceRegistration";
            
            #line default
            #line hidden
            
            #line 19 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.SelectCommand = "SELECT * FROM userData";
            
            #line default
            #line hidden
            @__ctrl.ConnectionString = global::System.Convert.ToString(System.Web.Compilation.ConnectionStringsExpressionBuilder.GetConnectionString("RegistrationConnectionString"), global::System.Globalization.CultureInfo.CurrentCulture);
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        442,
                        204,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("    \r\n    </div>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        646,
                        26,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control9(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = global::System.Drawing.Color.Gainsboro;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CommandField @__BuildControl__control11() {
            global::System.Web.UI.WebControls.CommandField @__ctrl;
            
            #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CommandField();
            
            #line default
            #line hidden
            
            #line 25 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.ShowSelectButton = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control12() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.DataField = "Id";
            
            #line default
            #line hidden
            
            #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.HeaderText = "Id";
            
            #line default
            #line hidden
            
            #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 26 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.SortExpression = "Id";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control13() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.DataField = "UserName";
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.HeaderText = "UserName";
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.SortExpression = "UserName";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control14() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 28 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 28 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.DataField = "Email";
            
            #line default
            #line hidden
            
            #line 28 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.HeaderText = "Email";
            
            #line default
            #line hidden
            
            #line 28 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.SortExpression = "Email";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control15() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.DataField = "Password";
            
            #line default
            #line hidden
            
            #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.HeaderText = "Password";
            
            #line default
            #line hidden
            
            #line 29 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.SortExpression = "Password";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control16() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 30 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 30 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.DataField = "Country";
            
            #line default
            #line hidden
            
            #line 30 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.HeaderText = "Country";
            
            #line default
            #line hidden
            
            #line 30 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.SortExpression = "Country";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control10(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.CommandField @__ctrl1;
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl1 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl2 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl3 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl4;
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl4 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl5;
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl5 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl6;
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl6 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control17(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(204, 204, 204)));
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Black;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control18(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(0, 0, 132)));
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.White;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control19(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(153, 153, 153)));
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Black;
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control20(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(238, 238, 238)));
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Black;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control21(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(0, 138, 140)));
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.White;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control22(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(241, 241, 241)));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control23(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(0, 0, 169)));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control24(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(202, 201, 201)));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control25(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(0, 0, 101)));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlGridView1() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            
            #line default
            #line hidden
            this.GridView1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.ID = "GridView1";
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.AllowPaging = true;
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.AllowSorting = true;
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.AutoGenerateColumns = false;
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BackColor = global::System.Drawing.Color.White;
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BorderColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(153, 153, 153)));
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BorderStyle = global::System.Web.UI.WebControls.BorderStyle.None;
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.BorderWidth = new System.Web.UI.WebControls.Unit(1D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.CellPadding = 3;
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.DataKeyNames = new string[] {
                    "Id"};
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.DataSourceID = "SqlDataSourceRegistration";
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Vertical;
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control9(@__ctrl.AlternatingRowStyle);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control10(@__ctrl.Columns);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control17(@__ctrl.FooterStyle);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control18(@__ctrl.HeaderStyle);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control19(@__ctrl.PagerStyle);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control20(@__ctrl.RowStyle);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control21(@__ctrl.SelectedRowStyle);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control22(@__ctrl.SortedAscendingCellStyle);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control23(@__ctrl.SortedAscendingHeaderStyle);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control24(@__ctrl.SortedDescendingCellStyle);
            
            #line default
            #line hidden
            
            #line 22 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.@__BuildControl__control25(@__ctrl.SortedDescendingHeaderStyle);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        672,
                        1635,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2307,
                        6,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl2;
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl2 = this.@__BuildControlSqlDataSourceRegistration();
            
            #line default
            #line hidden
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl3 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl4;
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl4 = this.@__BuildControlGridView1();
            
            #line default
            #line hidden
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl5 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        391,
                        1929,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control27() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2320,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(menager_aspx @__ctrl) {
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl4 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__ctrl5 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Menager.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.menager_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -121774970;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
