//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.6.1")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_3i1ky41m {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_3i1ky41m() {
        }
        
        static object Create_ASP_users_aspx() {
            return new ASP.users_aspx();
        }
        
        static object Create_ASP_loginpage_aspx() {
            return new ASP.loginpage_aspx();
        }
        
        static object Create_ASP_registration_aspx() {
            return new ASP.registration_aspx();
        }
        
        static object Create_ASP_menager_aspx() {
            return new ASP.menager_aspx();
        }
    }
}
