#pragma checksum "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "55C22E90D28958C166B14EE1429F0F358D5A88A6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class _Default : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 13 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
    protected global::System.Web.UI.WebControls.Label L_welcome;
    
    #line default
    #line hidden
    
    
    #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
    protected global::System.Web.UI.WebControls.Button B_logout;
    
    #line default
    #line hidden
    
    
    #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 334 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 341 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 13 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 347 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 13 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 346 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 335 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 13 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 13 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 340 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 13 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class users_aspx : global::_Default, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.users_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public users_aspx() {
            string[] dependencies;
            
            #line 912304 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Users.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.users_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Users.aspx";
                dependencies[1] = "~/Users.aspx.cs";
                global::ASP.users_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.users_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        93,
                        68,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=15.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.users_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.users_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        188,
                        15,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        161,
                        51,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        212,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <div>\r\n    \r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        258,
                        27,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlL_welcome() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 13 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.L_welcome = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 13 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl.ID = "L_welcome";
            
            #line default
            #line hidden
            
            #line 13 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl.Text = "Welcome...";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        285,
                        71,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    \r\n    </div>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        356,
                        28,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlB_logout() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.B_logout = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl.ID = "B_logout";
            
            #line default
            #line hidden
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl.Text = "Logout";
            
            #line default
            #line hidden
            
            #line 16 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl.Click += new System.EventHandler(this.B_logout_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        384,
                        82,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        466,
                        6,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl1 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl2 = this.@__BuildControlL_welcome();
            
            #line default
            #line hidden
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl3 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl4;
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl4 = this.@__BuildControlB_logout();
            
            #line default
            #line hidden
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl5 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 10 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        226,
                        253,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        479,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(users_aspx @__ctrl) {
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl4 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__ctrl5 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Users.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.users_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1265688271;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
