#pragma checksum "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D806C536215ABE0F24DA1DD176F6F5DEB842695B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Registration : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
    
    #line default
    #line hidden
    
    
    #line 41 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.TextBox userNameId;
    
    #line default
    #line hidden
    
    
    #line 47 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
    
    #line default
    #line hidden
    
    
    #line 49 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
    
    #line default
    #line hidden
    
    
    #line 55 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.TextBox emailId;
    
    #line default
    #line hidden
    
    
    #line 61 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
    
    #line default
    #line hidden
    
    
    #line 67 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.TextBox passId;
    
    #line default
    #line hidden
    
    
    #line 73 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
    
    #line default
    #line hidden
    
    
    #line 75 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.CompareValidator CompareValidator1;
    
    #line default
    #line hidden
    
    
    #line 81 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.TextBox confirmPassId;
    
    #line default
    #line hidden
    
    
    #line 87 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
    
    #line default
    #line hidden
    
    
    #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.DropDownList selectCountryId;
    
    #line default
    #line hidden
    
    
    #line 109 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.WebControls.Button submitResgister;
    
    #line default
    #line hidden
    
    
    #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 334 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 341 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 347 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 346 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 335 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 340 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class registration_aspx : global::Registration, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.registration_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public registration_aspx() {
            string[] dependencies;
            
            #line 912304 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Registration.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.registration_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Registration.aspx";
                dependencies[1] = "~/Registration.aspx.cs";
                global::ASP.registration_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.registration_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        104,
                        68,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=15.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.registration_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.registration_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        199,
                        15,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
    <style type=""text/css"">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 211px;
            text-align: right;
        }
        #Reset1 {
            margin-left: 78px;
        }
        #resetRegistration {
            height: 37px;
            width: 80px;
            margin-left: 77px;
        }
    </style>
");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        214,
                        388,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl2;
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        172,
                        437,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        609,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
    <div>
    
        <br />
    
        <table class=""auto-style1"">
            <tr>
                <td class=""auto-style2"">&nbsp;</td>
                <td><span id=""MainContent_RegisterUser_CreateUserStepContainer_ctl01"" class=""field-validation-error"" data-val=""true"" data-val-controltovalidate=""MainContent_RegisterUser_CreateUserStepContainer_UserName"" data-val-errormessage=""The user name field is required."" data-val-evaluationfunction=""RequiredFieldValidatorEvaluateIsValid"" data-val-initialvalue="""" style=""visibility: visible;"">.");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        655,
                        549,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "RequiredFieldValidator1";
            
            #line default
            #line hidden
            
            #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ControlToValidate = "userNameId";
            
            #line default
            #line hidden
            
            #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ErrorMessage = "The user name field is required";
            
            #line default
            #line hidden
            
            #line 35 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1204,
                        195,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    </span></td>\r\n            </tr>\r\n            <tr>\r\n        " +
                    "        <td class=\"auto-style2\">User name</td>\r\n                <td>\r\n          " +
                    "          ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1399,
                        171,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControluserNameId() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 41 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.userNameId = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 41 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "userNameId";
            
            #line default
            #line hidden
            
            #line 41 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 41 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.TextChanged += new System.EventHandler(this.userNameId_TextChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1570,
                        111,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">&nbsp;</td>\r\n                <td>\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1681,
                        157,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator2() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 47 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 47 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "RequiredFieldValidator2";
            
            #line default
            #line hidden
            
            #line 47 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ControlToValidate = "emailId";
            
            #line default
            #line hidden
            
            #line 47 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ErrorMessage = "The email address field is required.";
            
            #line default
            #line hidden
            
            #line 47 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1838,
                        197,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    <br />\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2035,
                        50,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegularExpressionValidator1() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            
            #line 49 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            
            #line default
            #line hidden
            this.RegularExpressionValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 49 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "RegularExpressionValidator1";
            
            #line default
            #line hidden
            
            #line 49 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ControlToValidate = "emailId";
            
            #line default
            #line hidden
            
            #line 49 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ErrorMessage = "Please Enter valid Email";
            
            #line default
            #line hidden
            
            #line 49 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 49 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ValidationExpression = "\\w+([-+.\']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2085,
                        265,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">Email address</td>\r\n                <td>\r\n                 " +
                    "   ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2350,
                        164,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlemailId() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 55 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.emailId = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 55 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "emailId";
            
            #line default
            #line hidden
            
            #line 55 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Email;
            
            #line default
            #line hidden
            
            #line 55 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2514,
                        86,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">&nbsp;</td>\r\n                <td>\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2600,
                        157,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator3() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 61 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 61 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "RequiredFieldValidator3";
            
            #line default
            #line hidden
            
            #line 61 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ControlToValidate = "passId";
            
            #line default
            #line hidden
            
            #line 61 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ErrorMessage = "The password field is required.";
            
            #line default
            #line hidden
            
            #line 61 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2757,
                        191,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">Password</td>\r\n                <td>\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2948,
                        159,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlpassId() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 67 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.passId = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 67 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "passId";
            
            #line default
            #line hidden
            
            #line 67 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            
            #line 67 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3107,
                        88,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">&nbsp;</td>\r\n                <td>\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3195,
                        157,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator4() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 73 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 73 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "RequiredFieldValidator4";
            
            #line default
            #line hidden
            
            #line 73 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ControlToValidate = "confirmPassId";
            
            #line default
            #line hidden
            
            #line 73 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ErrorMessage = "The confirm password field is required.";
            
            #line default
            #line hidden
            
            #line 73 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3352,
                        206,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    <br />\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3558,
                        50,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompareValidator1() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 75 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompareValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 75 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "CompareValidator1";
            
            #line default
            #line hidden
            
            #line 75 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ControlToCompare = "passId";
            
            #line default
            #line hidden
            
            #line 75 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ControlToValidate = "confirmPassId";
            
            #line default
            #line hidden
            
            #line 75 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ErrorMessage = " The password and confirmation password do not match.";
            
            #line default
            #line hidden
            
            #line 75 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3608,
                        228,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">Confirm password</td>\r\n                <td>\r\n              " +
                    "      ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3836,
                        167,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlconfirmPassId() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 81 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.confirmPassId = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 81 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "confirmPassId";
            
            #line default
            #line hidden
            
            #line 81 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(22D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 81 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            
            #line 81 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4003,
                        109,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">&nbsp;</td>\r\n                <td>\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4112,
                        157,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator5() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 87 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator5 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 87 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "RequiredFieldValidator5";
            
            #line default
            #line hidden
            
            #line 87 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ControlToValidate = "selectCountryId";
            
            #line default
            #line hidden
            
            #line 87 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ErrorMessage = "Select your country";
            
            #line default
            #line hidden
            
            #line 87 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 87 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.InitialValue = "Selcect Country";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4269,
                        219,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">Country</td>\r\n                <td>\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4488,
                        158,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control20() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 94 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 94 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Value = "Selcect Country";
            
            #line default
            #line hidden
            
            #line 94 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Text = "Selcect Country";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control21() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 95 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 95 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Text = "Bangladesh";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control22() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 96 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 96 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Text = "India";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control23() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 97 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 97 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Text = "Pakistan";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control24() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 98 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 98 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Text = "Afganistan";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control19(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl1 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl2 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl3 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl4 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl5;
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl5 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlselectCountryId() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.selectCountryId = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "selectCountryId";
            
            #line default
            #line hidden
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 93 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            this.@__BuildControl__control19(@__ctrl.Items);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4646,
                        456,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control25() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                </td>
            </tr>
            <tr>
                <td class=""auto-style2"">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class=""auto-style2"">&nbsp;</td>
                <td>
                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5102,
                        280,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlsubmitResgister() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 109 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.submitResgister = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 109 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "submitResgister";
            
            #line default
            #line hidden
            
            #line 109 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(35D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 109 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Text = "Register";
            
            #line default
            #line hidden
            
            #line 109 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(96D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 109 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.Click += new System.EventHandler(this.submitResgister_Click1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5382,
                        126,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n&nbsp;<input id=\"resetRegistration\" type=\"reset\" value=\"reset\" /></td>\r\n       " +
                    "     </tr>\r\n        </table>\r\n    \r\n    </div>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5508,
                        133,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl2;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl2 = this.@__BuildControlRequiredFieldValidator1();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl3 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl4 = this.@__BuildControluserNameId();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl5 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl6;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl6 = this.@__BuildControlRequiredFieldValidator2();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl7 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl8;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl8 = this.@__BuildControlRegularExpressionValidator1();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl9 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl10 = this.@__BuildControlemailId();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl11 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl12;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl12 = this.@__BuildControlRequiredFieldValidator3();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl13 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl14 = this.@__BuildControlpassId();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl15 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl16;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl16 = this.@__BuildControlRequiredFieldValidator4();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl17 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl18;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl18 = this.@__BuildControlCompareValidator1();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl19;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl19 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl20;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl20 = this.@__BuildControlconfirmPassId();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl20);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl21;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl21 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl21);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl22;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl22 = this.@__BuildControlRequiredFieldValidator5();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl22);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl23;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl23 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl23);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl24;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl24 = this.@__BuildControlselectCountryId();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl24);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl25;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl25 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl25);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl26;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl26 = this.@__BuildControlsubmitResgister();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl26);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl27;
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl27 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 27 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl27);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        623,
                        5025,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control27() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5648,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(registration_aspx @__ctrl) {
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl4 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__ctrl5 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 1 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "F:\Study\TF_3.1\my\Web_Lab\ASP project\final_try\Login_Registration\Registration.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.registration_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1680461563;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
